### ISSUE TITLE
Support RHDF5LIB_RPATH in pkgconfig

### ISSUE THREAD

**Issue by LTLA** [Huber-group-EMBL/Rhdf5lib#1]
For example, in _Rhtslib_, `RHTSLIB_RPATH` is supported in `pkgconfig` in case manual specification of the path is necessary (e.g., when the path discovered during compilation is not the same as the path during an R session, especially on clusters where head nodes have lots of softlinks).

**Comment by grimbough** [comment]
Hopefully this is addressed in commit [51470e](https://github.com/grimbough/Rhdf5lib/commit/51470ef7bf9d5731829abc43aa8dc415f6a6b4ff).  I'll puish it to bioc once I've done a bit more testing.

**Comment by LTLA** [comment]
Sweet, thanks.
