### ISSUE TITLE
Issue linking to both libnetcdf and Rhdf5lib

### ISSUE THREAD

**Issue by sneumann** [Huber-group-EMBL/Rhdf5lib#12]
Hi, we have an issue in mzR which is using Rhdf5lib (and libnetcdf).

The issue is that mzR Makevars has
`PKG_LIBS=$(PWIZ_LDFLAGS) $(RHDF5_LIBS) $(NC_LIBS)  $(ARCH_LIBS)`
which links to both `Rhdf5lib/lib/libhdf5.a` 
and `-L/usr/lib/x86_64-linux-gnu/hdf5/serial -lnetcdf -lhdf5`,
which can (and do) have incompatible versions/symbols. 

For details including package build output see https://github.com/Bioconductor/bioc_docker/issues/56
and https://github.com/sneumann/mzR/issues/177.

=> Any ideas how to avoid these duplicated HDF5 ? 
Thanks in advance, yours, Steffen

**Comment by grimbough** [comment]
Do you actually need to link to Rhdf5lib if `-lhdf5` is already included from the netcdf libs?

**Comment by sneumann** [comment]
Hi, indeed, If I had everything under control, I could compile 
against just one set of headers and link to the corresponding libs.

But I need to link against libnetcdf.so to be able to open `*.cdf` files. 
The LDFLAGS are coming from `nc-config`. The issue is that libnetcdf 
itself is linked against its own libhdf5:
```
sneumann@msbi-corei:~/src/jmzTab-m$ nc-config --libs
-L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lnetcdf -lhdf5_hl -lhdf5 -lpthread -lsz -lz -ldl -lm -lcurl
sneumann@msbi-corei$ ldd /usr/lib/x86_64-linux-gnu/libnetcdf.so.13 | grep hdf
	libhdf5_serial_hl.so.100 => /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so.100 (0x00007f1cb063e000)
	libhdf5_serial.so.100 => /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.100 (0x00007f1cb00e6000)

sneumann@msbi-corei:~/src/jmzTab-m$ ls -l /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so
lrwxrwxrwx 1 root root 23 Aug 13  2017 /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so -> ../../libhdf5_serial.so
```
So things would be fine if the Rhdf5lib were compiled against the installed `libhdf-dev`.
I guess you included your own copy exactly to avoid those dependencies ...
Yours,
Steffen

**Comment by grimbough** [comment]
This is a pretty horrid scenario, it would be so much easier if `nc-config` just listed the `-lhdf5_cpp` and you could guarantee it was there if **netcdf** was present.  You absolutely right that bundling HDF5 into **Rhdf5lib** is supposed to make sure all users have the same version, but it's a nightmare here.  

Is it sufficient to remove any reference to **Rhdf5lib** add `-lhdf5_cpp` to `Makevars` as I've done in https://github.com/grimbough/mzR/blob/5029d870d788f11ba4cfb973f4f03f81b220590d/src/Makevars#L140 ?

That builds for me on Ubuntu 16.04 and Mac OSX where I've installed netcdf via `apt-get install netcdf-dev` and `brew install netcdf` respectively.  It seems unlikely that `libhdf5.so` will be present and `libhdf5_cpp.so` is not, but I guess it isn't guaranteed, so maybe some additional check is also required.

---

I can't get a source build of **mzR** working at all on Windows, but I think that isn't related to HDF5 for now.  My compilation fails trying to find `netcdf.h`, and while I can see it in `src/win/x64` it doesn't seem to be picked up by the compiler.

**Comment by sneumann** [comment]
Hi, your windows issue sounds like https://github.com/sneumann/mzR/issues/50,
which should at least have pointers where to download and put the netCDF stuff. 
I am surprised we still have the mzR/src/win/* stuff in there. 

I have started to migrate the netCDF interface in mzR to the `ncdf4` package, 
https://github.com/sneumann/mzR/tree/featureRemovelibnetCDF
otherwise that issue will come back haunting us, and it was much easier 
than I had thought. 

Sorry for the noise here, and thanks for your efforts investigating it.
