### ISSUE TITLE
Couldn't install  Rhdf5lib on win32 and win64 at the same time 

### ISSUE THREAD

**Issue by zyb1984** [Huber-group-EMBL/Rhdf5lib#17]
Dear professor, 
    Couldn't install  Rhdf5lib on win32 and win64 at the same time.
    First, I tried to  install  Rhdf5lib with Rstudio, and  the packages couldn't load in the R i386 3.6.0 environment.
   Second, I tried to  install  Rhdf5lib with  source code, if install on Ri64 3.6.0, the packages couldn't load in the R i386 3.6.0 environment. if install on Ri386 3.6.0, the packages couldn't load in the R i64 3.6.0 environment. 
 Also during install  with  source code, several warning had mentioned, 
" pkgconfig: no visible global function definition for 'shortPathName'
Undefined global functions or variables:
  shortPathName
Consider adding
  importFrom("utils", "shortPathName")"

**Comment by grimbough** [comment]
Thanks for the report.  Can you provide the commands you used to install **Rhdf5lib**, and the complete error messages you're receiving.  

The binary versions available via Bioconductor should be built and tested on both 32-bit and 64-bit.  If you're building from source then you probably need to specify that the installation is for both architectures, but I'll be able to help more if you provide the extra details.

**Comment by zyb1984** [comment]
* installing *source* package 'Rhdf5lib' ...   ** using staged installation   untarring hdf5_headers_1.10.3.tar.gz ...   ** libs   Warning: this package has a non-empty   'configure.win' file,   so building only the main architecture       mkdir -p "C:/Program   Files/R/R-3.6.0/library/00LOCK-Rhdf5lib/00new/Rhdf5lib/lib/x64/"   "C:/Program Files/R/R-3.6.0/library/00LOCK-Rhdf5lib/00new/Rhdf5lib/include"   cp "winlib/x64/libhdf5.a"   "C:/Program   Files/R/R-3.6.0/library/00LOCK-Rhdf5lib/00new/Rhdf5lib/lib/x64/libhdf5.a"   cp "winlib/x64/libhdf5_cpp.a"   "C:/Program   Files/R/R-3.6.0/library/00LOCK-Rhdf5lib/00new/Rhdf5lib/lib/x64/libhdf5_cpp.a"   cp "winlib/x64/libszip.a"   "C:/Program   Files/R/R-3.6.0/library/00LOCK-Rhdf5lib/00new/Rhdf5lib/lib/x64/libszip.a"   cp ./hdf5/*.h "C:/Program   Files/R/R-3.6.0/library/00LOCK-Rhdf5lib/00new/Rhdf5lib/include"   cp ./hdf5/c++/*.h "C:/Program   Files/R/R-3.6.0/library/00LOCK-Rhdf5lib/00new/Rhdf5lib/include"   c:/Rtools/mingw_64/bin/gcc    -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG       -I./hdf5   -O2 -Wall    -std=gnu99 -mtune=generic -c Rhdf5lib.c -o Rhdf5lib.o   c:/Rtools/mingw_64/bin/gcc -shared -s   -static-libgcc -o Rhdf5lib.dll tmp.def Rhdf5lib.o winlib/x64/libhdf5.a   winlib/x64/libszip.a -lpsapi -lz -LC:/PROGRA~1/R/R-36~1.0/bin/x64 -lR   installing to C:/Program   Files/R/R-3.6.0/library/00LOCK-Rhdf5lib/00new/Rhdf5lib/libs/x64   ** R   ** inst   ** byte-compile and prepare package for lazy   loading   ** help   *** installing help indices       converting help for package 'Rhdf5lib'       finding   HTML links ... 好了         Rhdf5lib                                  html           getHdf5Version                            html           pkgconfig                                 html     ** building package indices   ** installing vignettes   ** testing if installed package can be loaded   from temporary location   ** testing if installed package can be loaded   from final location   ** testing if installed package keeps a record of   temporary installation path   * DONE (Rhdf5lib)
--

**Comment by zyb1984** [comment]
>   Rcmd check Rhdf5lib ##check the “Rhdf5lib_1.7.0.tar.gz” source code  
>   Rcmd INSTALL Rhdf5lib  ## install 

and Warning in  log
* checking if this is a source package ... WARNING
Subdirectory 'Rhdf5lib/src' contains apparent object files/libraries
  Rhdf5lib.dll Rhdf5lib.o
Object files/libraries should not be included in a source package.

In addition to the above warning(s), found the following notes:

Found the following apparent object files/libraries:
  src/winlib/i386/libhdf5.a src/winlib/i386/libhdf5_cpp.a
  src/winlib/i386/libszip.a src/winlib/x64/libhdf5.a
  src/winlib/x64/libhdf5_cpp.a src/winlib/x64/libszip.a
Object files/libraries should not be included in a source package.
* checking if there is a namespace ... OK
* checking for executable files ... WARNING
Found the following executable files:
  src/Rhdf5lib.dll
  src/Rhdf5lib.o
Source packages should not contain undeclared executable files.
See section 'Package structure' in the 'Writing R Extensions' manual.
pkgconfig: no visible global function definition for 'shortPathName'
Undefined global functions or variables:
  shortPathName
Consider adding
  importFrom("utils", "shortPathName")

**Comment by grimbough** [comment]
Is there a reason you're trying to install the source package on Windows.  It's generally easier to install the pre-built binary version as compiling the source code can require some extra tools for Windows.

My recommended installation is to use:

```r
install.packages('BiocManager')
BiocManager::install('Rhdf5lib')
```

This should install for both 32-bit and 64-bit architectures on Windows.

---

If you really want to isntall from source then I think you'll need the `--force-biarch` argument to make sure both architectures are installed e.g.

```
R CMD INSTALL --force-biarch Rhdf5lib_1.7.0.tar.gz
```

**Comment by zyb1984** [comment]
Today is ok, Thank you very much.
   Few days again, I tried the traditional installing method with BiocManger, but If install under Rstudio, the Rhdf5lib package in R x64 could be load , but the Rhdf5lib package in R i386 couldn't be load, and mistake is "couln't find the inch of  Rhdf5lib "

**Comment by zyb1984** [comment]
Dear professor ,
   I tried to install 'Rhdf5lib' with traditional method, and "BiocManager::install('Rhdf5lib')" in Rsutio, no mistake mentioned, but couldn't be load in Ri386 3.6.0 , and mistake is "no packages "Rhdf5lib" been installed in 'arch=i386'.
   But in Rx64 3.6.0, all is ok, no mistake mentioned.
   Also the same questions in "rhdf5", and  mistake is " no dll for "Rhdf5lib" ".

**Comment by grimbough** [comment]
How does this work for you?

```r
BiocManager::install('grimbough/Rhdf5lib', INSTALL_opts = "--force-biarch")
```

I get lots of output, but it ends with some tests for both architectures e.g.

```
...
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (Rhdf5lib)
```

If you're still getting errors please include both the command you're running and the full output here.

**Comment by zyb1984** [comment]
Thank you very much, I had solve the problem with install Anaconda instead python.
