### ISSUE TITLE
Fails to install in lib path with space

### ISSUE THREAD

**Issue by stanstrup** [Huber-group-EMBL/Rhdf5lib#18]
Installing from source fails where there are space in the lib path.
Note the last line where it thinks the path starts with `App/`.

```r
mkdir -p "/srv/shiny-server/QC4Metabolomics/Shiny App/packrat/lib/x86_64-pc-linux-gnu/3.6.0/00LOCK-Rhdf5lib/00new/Rhdf5lib/include"
cp hdf5/src/*.h /srv/shiny-server/QC4Metabolomics/Shiny App/packrat/lib/x86_64-pc-linux-gnu/3.6.0/00LOCK-Rhdf5lib/00new/Rhdf5lib/include
cp: target 'App/packrat/lib/x86_64-pc-linux-gnu/3.6.0/00LOCK-Rhdf5lib/00new/Rhdf5lib/include' is not a directory
```

It looks like there are missing brackets somewhere causing this. If I remove the space in the lib path the it works.

**Comment by grimbough** [comment]
Does this works for you?

```r
BiocManager::install('grimbough/Rhdf5lib', ref='spaces')
```

**Comment by stanstrup** [comment]
Yep that solved it. Thanks!

**Comment by grimbough** [comment]
Thanks for the bug report and confirmation that it is working now.  I'll merge the change into the versions on Bioconductor shortly.

**Comment by scottgigante** [comment]
This is still an issue as of October 3 on Bioconductor version 3.9 (BiocManager 1.30.4), R 3.6.1 (2019-07-05). Installing from master solves the problem.
