### ISSUE TITLE
Don't use fixed directories for zlib.h lookup

### ISSUE THREAD

**Issue by landesfeind** [Huber-group-EMBL/Rhdf5lib#20]
Installing the package fails if the `zlib.h` is not in one of your requested paths. In particular, you require it to be in 
```
ZLIB_HOME=/usr/local
if test ! -f "${ZLIB_HOME}/include/zlib.h"
then
        ZLIB_HOME=/usr
fi
```
(see https://github.com/grimbough/Rhdf5lib/blob/master/configure#L3817); introduced here: https://github.com/grimbough/Rhdf5lib/pull/16/commits/ea9d159e03e8fe35bcbd3da1272f183e4cda2b88#diff-02ea2ecda48bd359bfdd9cbcab6f7b01R84

This may not be the case in non-standard build environments, e.g., when compiling the library in a Conda-Environment while not having zlib installed globally.

# Workaround
Link the library into the desired location, e.g.:
```
ln -s /path/to/true/zlib.h /usr/local/include/zlib.h
```
After compilation, drop the link again:
```
rm /usr/local/include/zlib.h
```

# System information
```
> R.version
               _
platform       x86_64-pc-linux-gnu
arch           x86_64
os             linux-gnu
system         x86_64, linux-gnu
status
major          3
minor          6.0
year           2019
month          04
day            26
svn rev        76424
language       R
version.string R version 3.6.0 (2019-04-26)
nickname       Planting of a Tree
> BiocManager::version()
[1] ‘3.9’
> packageVersion("Rhdf5lib")
[1] ‘1.6.0’
```

**Comment by grimbough** [comment]
Thanks for pointing this out. I hadn't merged a change addressing this from the zlib branch.

You should be able to specify a non-standard location for the zlib library with the argument `--with-zlib=/path/to/true/`. 

I find it quite hard to emulate an environment without zlib, so would you mind testing this for me and reporting back.  The complete argument to install will be something like:

```r
BiocManager::install('grimbough/Rhdf5lib', configure.args = "--with-zlib='/tmp/zlib/'")
```

**Comment by landesfeind** [comment]
With the commit 29a2eb4, the issue seems to be resolved. I tried to compile in the very same circumstances than before (i.e., having the "workaround-link" removed) and it now correctly identifies presence of `zlib.h`:
```
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
```
I think it just let the compile figure out if it is available which is the very correct way.

Thank you so much for the quick answer and the quick fix!
