### ISSUE TITLE
Install error on R-devel-ATC

### ISSUE THREAD

**Issue by mahendra-mariadassou** [Huber-group-EMBL/Rhdf5lib#24]
I maintain a CRAN [package](https://cran.r-project.org/web/packages/PLNmodels/) that depends on a bioconductor package depending itself on `Rhdf5lib`. CRAN warned us that our package has an [error](https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64-gcc8/PLNmodels-00install.html) with the new r-devel-gcc8 (also called r-devel-ATC for Alternative Tool Chain) for Windows. The package builds correctly but fails to load from the temporary location with the following error  

> Error: package or namespace load failed for 'PLNmodels' in library.dynam(lib, package, package.lib):
> DLL 'Rhdf5lib' not found: maybe not installed for this architecture?
> Error: loading failed

Everything works fine with other versions (including r-devel for Windows with the current toolchain). 

From my limited understanding, the error stems from the current `rhdf5lib` windows binaries being [built](https://github.com/grimbough/Rhdf5lib/tree/master/vignettes) with [Rtools3.5](https://cran.r-project.org/bin/windows/Rtools/) which differs from the [alternative toolchain Rtools40](https://github.com/r-windows/rtools-installer). In particular, the new toolchains comes with its own [pacman packages](https://github.com/r-windows/rtools-packages), including [one for hdf5](https://github.com/r-windows/rtools-packages/tree/master/mingw-w64-hdf5). 

I don't know if other users reported similar problems or if you have any insights regarding the error.

**Comment by grimbough** [comment]
Rhdf5lib ships with prebuilt Windows binaries of libhdf5 that I've created with the old toolchain.  I guess I need to built them using the ATC as well, although currently I've no idea how to select which binary to use when installing. I presume I can work something based on the CC version, but I can't speak for how stable that will be. 

Rhdf5lib isn't the only Bioconductor package that uses this precompiled binary strategy, so I'll bring the issue up in our next developers call & see if anyone else has any insights.

**Comment by jeroen** [comment]
I can send a PR if you'd like.

**Comment by jeroen** [comment]
Actually there is no problem because the libs that you link to are not ABI sensitive. So the same prebuilt libs will work with the old and new toolchain.

The CRAN error appears only because CRAN needs to build `Rhdf5lib` using `--merge-multiarch`. I've asked them to do so.

**Comment by mahendra-mariadassou** [comment]
Ah OK. Thank you very much for taking the time to look into it!
