### ISSUE TITLE
retrieve the h5 lib paths

### ISSUE THREAD

**Issue by mikejiang** [Huber-group-EMBL/Rhdf5lib#30]
according to https://github.com/grimbough/Rhdf5lib/blob/master/vignettes/Rhdf5lib.Rmd, this is recommended way of retrieving h5 static libs path
```bash
RHDF5_LIBS=$(shell echo 'Rhdf5lib::pkgconfig("PKG_CXX_LIBS")'|\
        "${R_HOME}/bin/R" --vanilla --slave)  
```
Here is my use case, which confuses the user and myself quite a bit and cost quite some troubleshooting efforts:
On the HPC server, this is the default system R lib path, which has Rhdf5lib 1.8 installed
```r
> .libPaths()
[1] "/app/easybuild/software/R/3.6.2-foss-2016b/lib/R/library"
```
And I installed Rhdf5lib 1.11  into my personal R lib path ~/mypath, and put it before system path by setting .libPaths()  in my .Rprofile file, i.e.
```r
> .libPaths()
[1] "/home/wjiang2/mypath/3.6"         
[2] "/app/easybuild/software/R/3.6.2-foss-2016b/lib/R/library"
```
Then when I `R CMD INSTALL ncdfFlow` , it gives me h5 lib mismatch error Headers are 1.10.6, library is 1.10.5. Because `Rhdf5lib::pkgconfig` call was invoked with `--vanilla`, which essentially ignores the customized `.libPaths()`  set in `.Rprofile` file, causing linking to the older h5 lib from system R lib path (i.e. `3.6.2-foss-2016b/lib/R/library` ) while the header is from `mypath/3.6` triggered by `LinkingTo` field in `DESCRIPTION`
My easy fix is to change `Makevar` to use `Rscript -e 'Rhdf5lib::pkgconfig("PKG_CXX_LIBS")'`, which I thought may be more robust? but I'd double check with you guys since that was how `HDF5Array` and many other bioc packages link to `Rhdf5lib`, and there must some deliberate considerations on this matter.

@mtmorgan @hpages

**Comment by mikejiang** [comment]
Also, based on https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-Makevars
>If you want to run R code in Makevars, e.g. to find configuration information, please do ensure that you use the correct copy of R or Rscript: there might not be one in the path at all, or it might be the wrong version or architecture. The correct way to do this is via
"$(R_HOME)/bin$(R_ARCH_BIN)/Rscript" filename
"$(R_HOME)/bin$(R_ARCH_BIN)/Rscript" -e ‘R expression’

**Comment by mikejiang** [comment]
Or, at least remove `--vanilla`, will that be more robust?

**Comment by hpages** [comment]
Looks like you have a fair point. Note that the vignettes in zlibbioc and Rhtslib also say to use `"${R_HOME}/bin/R" --vanilla --slave` (see [here](https://github.com/Bioconductor/zlibbioc/blob/974ef42f3ae552b8184f228b64a82f1b017ce83c/vignettes/UsingZlibbioc.Rnw#L95-L98) and [here](https://github.com/Bioconductor/Rhtslib/blob/4196fdebff259bb747b33b9d9ee2ea8f7686d915/vignettes/Rhtslib.Rmd#L89-L92)) so at least we are consistent ;-)

Note that for Rhtslib it's been the case since I took over maintenance of the package a couple of years ago and I never questioned it but I think that you're right that this is incorrect and that `${R_HOME}/bin/Rscript -e` should be used instead. This is what the R-exts manual says and what Rcpp client packages have been doing for years (according to the [Rcpp-package vignette](https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-package.pdf)).

@mtmorgan @grimbough Is the divergence from R-exts recommendation intended here or is this simply an overlook on our part?

**Comment by grimbough** [comment]
I'm pretty sure the implementation I use here was a straight copy from Rhtslib, I basically copied that package when I split the the HDF5 library out of rhdf5.  I even have this in the vignette

> Rhdf5lib is very much inspired by the zlibbioc and Rhtslib packages.

I'm happy to follow the R-exts recommendation.  My instinct says taking `--vanilla` away makes thing less robust, as a user could have anything in their `.Rprofile` but this is a case where it seems to be a hindrance.  I'm curious why it works OK on my systems, as I also set `.libPaths()` in `.Rprofile` and don't have much in the default library.  I don't have multiple package versions in different libraries though.

I guess we should note that Mike is deviating from the supported environment here by mixing R-3.6 with BioC 3.12.  I'm not sure it would be possible to get into this situation without breaking that rule, although I do it myself too.

**Comment by grimbough** [comment]
Taking a look, I don't even follow my own recommendation and use `$(R_HOME)/bin/Rscript" --vanilla -e ` in rhdf5 e.g. https://github.com/grimbough/rhdf5/blob/85bd00b57d3549f4cad39a06e007e6b4a21e3d0b/src/Makevars#L1

**Comment by mikejiang** [comment]
Thanks for replying. Looks like there is no special concern for me to remove `vanilla` at least. I am closing this for now.

**Comment by hpages** [comment]
@mikejiang @grimbough @mtmorgan FYI I've [updated the instructions in Rhtslib's vignette](https://github.com/Bioconductor/Rhtslib/commit/b9de22dc1eba44ed3ba8310e1d47a0fc3adbd7ed) and started to modify the `Makevars` of a few Rhtslib's clients e.g. Rsamtools, VariantAnnotation, etc...

**Comment by grimbough** [comment]
Thanks for the reminder and update @hpages. I've added this to my TODO list (https://github.com/users/grimbough/projects/1) and will update soon.
