### ISSUE TITLE
What exactly is included?

### ISSUE THREAD

**Issue by timothy-barry** [Huber-group-EMBL/Rhdf5lib#38]
Hi,

I tried to post to the Bioconductor support page, but the link seems to be broken. What parts of the library are included? In particular, are the high-level APIs, such as [HDF5 Lite](https://portal.hdfgroup.org/display/HDF5/HDF5+Lite+%28H5LT%29+Interface), included? What about [H5CPP](http://h5cpp.org/)? Thanks.

**Comment by grimbough** [comment]
You can examine the HDF5 source in the tarball in https://github.com/grimbough/Rhdf5lib/tree/master/src It's a stripped down version of the full source distribution that comes from HDF5 group directly.  

It includes the C and C++ libraries, but doesn't include anything that doesn't come from primary HDF5 distrbution, so there's no H5CPP.

Currently it distributes both the low- and high-level APIs so you should be able to use the HDF5 Lite interface.

I'm also happy to take requests if there's things missing that are useful.

----

Out of interest, where did you find a the broken link to the Bioconductor support page?  I'd like to fix that.

**Comment by timothy-barry** [comment]
That all makes sense. Thank you!

In the README it says: For bug reports, please register an issue here on Github. For usage queries please post a question on the Bioconductor Support Forum. The link "Bioconductor Support Forum" does not seem to work for me.

**Comment by grimbough** [comment]
Thanks, I've updated the link to point to the new support forum URL.
