### ISSUE TITLE
Installation failure: fatal error: iostream.h: No such file or directory

### ISSUE THREAD

**Issue by xxxcha** [Huber-group-EMBL/Rhdf5lib#43]
Hi I am currently installing Rhdf5lib package but I have compilation error as follows:
```r
H5DataSpace.cpp:15:10: fatal error: iostream.h: No such file or directory
   15 | #include <iostream.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:1035: H5DataSpace.lo] Error 1
make[3]: Leaving directory '/tmp/Rtmp3a5w9o/R.INSTALLfdf43ea004b/Rhdf5lib/src/hdf5/c++/src'
make[2]: *** [Makefile:1525: lib] Error 1
make[2]: Leaving directory '/tmp/Rtmp3a5w9o/R.INSTALLfdf43ea004b/Rhdf5lib/src/hdf5/c++/src'
make[1]: *** [Makefile:1261: lib] Error 1
make[1]: Leaving directory '/tmp/Rtmp3a5w9o/R.INSTALLfdf43ea004b/Rhdf5lib/src/hdf5/c++'
make: *** [Makefile:1100: lib] Error 1
configure: error: "Failed to compiled the HDF5 library"
```
I run R code on Ubuntu 20.04 and my C++ compiler is x86_64-conda-linux-gnu-c++ -std=gnu++14.
Is there any solution to this problem? I appreciate your help.

**Comment by tcvenables** [comment]
I ran into similar problem and i think it was because of conda.  I used
conda install -c bioconda bioconductor-rhdf5lib
and it resolved the issue

**Comment by grimbough** [comment]
I should have replied to this a long time ago!

As noted above, if you're using R installed with conda the recommended way to install packages is via `conda install`.  Otherwise there are often problems finding compilers, libraries, headers, etc.
