### ISSUE TITLE
Install error (libtool configuration)

### ISSUE THREAD

**Issue by kdkorthauer** [Huber-group-EMBL/Rhdf5lib#8]
Hi,

I'm trying to install **Rhdf5lib** from Bioconductor 3.7 (release) on linux. I'm getting an error as the package is being configured. From what I can tell, the relevant error message is: 

`libtool:   error: require no space between '-L' and '-L/n/helmod/apps/centos7/Core/pcre/8.37-fasrc02/lib'`

I checked to make sure pcre is loaded on the system, but otherwise I'm not sure what to try.

Here's my session info:
```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /usr/lib64/libblas.so.3.4.2
LAPACK: /usr/lib64/liblapack.so.3.4.2

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.30.0

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0   
> biocValid()
[1] TRUE
}
```

Any suggestions? Let me know if you need anymore info to help diagnose.

Best,
Keegan

**Comment by grimbough** [comment]
Thanks for the report. I'm away at the moment, but I'll take a look next week and report back.

**Comment by grimbough** [comment]
Can you add the output of running `echo $LDFLAGS` in a terminal.  I guess there's something already set on your system in addition to what gets generated during the package configure.

**Comment by kdkorthauer** [comment]
I get no output for `echo $LDFLAGS` in the terminal.

**Comment by grimbough** [comment]
Can you try capturing the output from the configure step.  I find the easiest way to do this is try the installation via `Rscript` in a terminal e.g.

```
Rscript -e 'BiocInstaller::biocLite("Rhdf5lib")' > /tmp/config_output.txt
```
Then either paste the output here, or attached the file directly if it's too long/ugly.

**Comment by kdkorthauer** [comment]
[config_output.txt](https://github.com/grimbough/Rhdf5lib/files/2050735/config_output.txt) contains the output from `BiocInstaller::biocLite("Rhdf5lib")`.

**Comment by grimbough** [comment]
Thanks for that.  It looks like the empty `-L` is included in the call to **gcc** used to build R, which Rhdf5lib copies and you can't currently alter.  I've created a branch so we can test passing setting this during installation, rather than blindly copying R's setting.

Does this get any further?

```{r}
BiocInstaller::biocLite('grimbough/Rhdf5lib', 
    ref = "passing_flags", 
    configure.vars = "CC='/n/helmod/apps/centos7/Core/gcc/7.1.0-fasrc01/bin/gcc -I/n/helmod/apps/centos7/Core/curl/7.45.0-fasrc01/include -I/n/helmod/apps/centos7/Core/bzip2/1.0.6-fasrc01/include -I/n/helmod/apps/centos7/Core/pcre/8.37-fasrc02/include -I/n/helmod/apps/centos7/Core/readline/6.3-fasrc02/include -L/n/helmod/apps/centos7/Core/bzip2/1.0.6-fasrc01/lib -L/n/helmod/apps/centos7/Core/pcre/8.37-fasrc02/lib -L/n/helmod/apps/centos7/Core/curl/7.45.0-fasrc01/lib -L/n/helmod/apps/centos7/Core/readline/6.3-fasrc02/lib64'")
```

**Comment by kdkorthauer** [comment]
Success! Thank you for all the help!

**Comment by grimbough** [comment]
Great, I'll tidy the branch up and then merge it into BioC-devel.  

It's a pain to have to set the `configure.vars` argument every time you need to re-install the package, but I think you could add the following to `~/.R/Makevars` and it'll use it automatically.

```
CC=/n/helmod/apps/centos7/Core/gcc/7.1.0-fasrc01/bin/gcc -I/n/helmod/apps/centos7/Core/curl/7.45.0-fasrc01/include -I/n/helmod/apps/centos7/Core/bzip2/1.0.6-fasrc01/include -I/n/helmod/apps/centos7/Core/pcre/8.37-fasrc02/include -I/n/helmod/apps/centos7/Core/readline/6.3-fasrc02/include -L/n/helmod/apps/centos7/Core/bzip2/1.0.6-fasrc01/lib -L/n/helmod/apps/centos7/Core/pcre/8.37-fasrc02/lib -L/n/helmod/apps/centos7/Core/curl/7.45.0-fasrc01/lib -L/n/helmod/apps/centos7/Core/readline/6.3-fasrc02/lib64
```

This shouldn't impact any of your existing packages as the empty `-L` entries we've removed don't actually do anything anyway.

**Comment by kdkorthauer** [comment]
Excellent; I'll add that to my Makevars. Thanks again!
